Traceback (most recent call last):
  File "/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import hls4ml

config = hls4ml.utils.config_from_keras_model(model, granularity='model')
print(config)
hls_model = hls4ml.converters.convert_from_keras_model(
    model, hls_config=config, output_dir='model_2/hls4ml_prj', part='xcu250-figd2104-2L-e'
)
hls_model.compile()
hls_model.build(csim=False)
------------------

----- stdout -----
WARNING: Failed to import handlers from convolution.py: No module named 'torch'.
WARNING: Failed to import handlers from core.py: No module named 'torch'.
Interpreting Sequential
Topology:
Layer name: fc1_input, layer type: InputLayer, input shapes: [[None, 16]], output shape: [None, 16]
Layer name: fc1, layer type: Dense, input shapes: [[None, 16]], output shape: [None, 64]
Layer name: relu1, layer type: Activation, input shapes: [[None, 64]], output shape: [None, 64]
Layer name: fc2, layer type: Dense, input shapes: [[None, 64]], output shape: [None, 32]
Layer name: relu2, layer type: Activation, input shapes: [[None, 32]], output shape: [None, 32]
Layer name: fc3, layer type: Dense, input shapes: [[None, 32]], output shape: [None, 32]
Layer name: relu3, layer type: Activation, input shapes: [[None, 32]], output shape: [None, 32]
Layer name: output, layer type: Dense, input shapes: [[None, 32]], output shape: [None, 5]
Layer name: softmax, layer type: Softmax, input shapes: [[None, 5]], output shape: [None, 5]
{'Model': {'Precision': 'fixed<16,6>', 'ReuseFactor': 1, 'Strategy': 'Latency', 'BramFactor': 1000000000, 'TraceOutput': False}}
Interpreting Sequential
Topology:
Layer name: fc1_input, layer type: InputLayer, input shapes: [[None, 16]], output shape: [None, 16]
Layer name: fc1, layer type: Dense, input shapes: [[None, 16]], output shape: [None, 64]
Layer name: relu1, layer type: Activation, input shapes: [[None, 64]], output shape: [None, 64]
Layer name: fc2, layer type: Dense, input shapes: [[None, 64]], output shape: [None, 32]
Layer name: relu2, layer type: Activation, input shapes: [[None, 32]], output shape: [None, 32]
Layer name: fc3, layer type: Dense, input shapes: [[None, 32]], output shape: [None, 32]
Layer name: relu3, layer type: Activation, input shapes: [[None, 32]], output shape: [None, 32]
Layer name: output, layer type: Dense, input shapes: [[None, 32]], output shape: [None, 5]
Layer name: softmax, layer type: Softmax, input shapes: [[None, 5]], output shape: [None, 5]
Creating HLS model
Writing HLS project
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
----- stderr -----
/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/hls4ml/converters/__init__.py:24: UserWarning: WARNING: Pytorch converter is not enabled!
  warnings.warn("WARNING: Pytorch converter is not enabled!", stacklevel=1)
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
----- stdout -----
Done
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mException[0m                                 Traceback (most recent call last)
Cell [0;32mIn[9], line 9[0m
[1;32m      5[0m hls_model [38;5;241m=[39m hls4ml[38;5;241m.[39mconverters[38;5;241m.[39mconvert_from_keras_model(
[1;32m      6[0m     model, hls_config[38;5;241m=[39mconfig, output_dir[38;5;241m=[39m[38;5;124m'[39m[38;5;124mmodel_2/hls4ml_prj[39m[38;5;124m'[39m, part[38;5;241m=[39m[38;5;124m'[39m[38;5;124mxcu250-figd2104-2L-e[39m[38;5;124m'[39m
[1;32m      7[0m )
[1;32m      8[0m hls_model[38;5;241m.[39mcompile()
[0;32m----> 9[0m [43mhls_model[49m[38;5;241;43m.[39;49m[43mbuild[49m[43m([49m[43mcsim[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m

File [0;32m/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/hls4ml/model/graph.py:854[0m, in [0;36mModelGraph.build[0;34m(self, **kwargs)[0m
[1;32m    850[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists([38;5;28mself[39m[38;5;241m.[39mconfig[38;5;241m.[39mget_output_dir()):
[1;32m    851[0m     [38;5;66;03m# Assume the project wasn't written before[39;00m
[1;32m    852[0m     [38;5;28mself[39m[38;5;241m.[39mwrite()
[0;32m--> 854[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconfig[49m[38;5;241;43m.[39;49m[43mbackend[49m[38;5;241;43m.[39;49m[43mbuild[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/hls4ml-tutorial/lib/python3.10/site-packages/hls4ml/backends/vivado/vivado_backend.py:193[0m, in [0;36mVivadoBackend.build[0;34m(self, model, reset, csim, synth, cosim, validation, export, vsynth, fifo_opt)[0m
[1;32m    191[0m     found [38;5;241m=[39m os[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mcommand -v vivado_hls > /dev/null[39m[38;5;124m'[39m)
[1;32m    192[0m     [38;5;28;01mif[39;00m found [38;5;241m!=[39m [38;5;241m0[39m:
[0;32m--> 193[0m         [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m'[39m[38;5;124mVivado HLS installation not found. Make sure [39m[38;5;124m"[39m[38;5;124mvivado_hls[39m[38;5;124m"[39m[38;5;124m is on PATH.[39m[38;5;124m'[39m)
[1;32m    195[0m curr_dir [38;5;241m=[39m os[38;5;241m.[39mgetcwd()
[1;32m    196[0m os[38;5;241m.[39mchdir(model[38;5;241m.[39mconfig[38;5;241m.[39mget_output_dir())

[0;31mException[0m: Vivado HLS installation not found. Make sure "vivado_hls" is on PATH.

